#!/usr/bin/env bash
# Displays information about listening ports, including listening sockets.
# Additionally, it provides the Process ID (PID) and the program name associated with each socket

netstat -l --program
