#!/usr/bin/env bash
# This script pings an IP address provided as an argument.
# If no argument is passed, it displays usage instructions:
# Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
# Otherwise, it pings the specified IP address five times.


if [ "$#" -lt "1" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping "$1" -c 5
fi
